name: flutter_flip_card
description: A component that provides a flip card animation. It could be used for hiding and showing details of a product.
version: 0.0.6
homepage: https://github.com/hodgeswt/flutter_flip_card

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
